"""
fast_logger.export
~~~~~~~~~~~~~~~~~~
Export recorded log sessions to HTML and Markdown reports.
"""

from __future__ import annotations

import html as html_mod
import json
import os
from datetime import datetime
from typing import Any

_LEVEL_COLORS = {
    "DEBUG": "#64748b",
    "INFO": "#3b82f6",
    "WARNING": "#f59e0b",
    "ERROR": "#ef4444",
    "CRITICAL": "#a855f7",
}

_HTML_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>FastLogger Report — {title}</title>
<style>
  :root {{
    --bg: #0f1117;
    --card: #1a1d27;
    --border: #2d3148;
    --text: #e2e8f0;
    --muted: #64748b;
    --DEBUG: #64748b;
    --INFO: #3b82f6;
    --WARNING: #f59e0b;
    --ERROR: #ef4444;
    --CRITICAL: #a855f7;
  }}
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{ background: var(--bg); color: var(--text); font-family: 'Segoe UI', system-ui, sans-serif; padding: 2rem; }}
  header {{ margin-bottom: 2rem; }}
  header h1 {{ font-size: 1.75rem; font-weight: 700; }}
  header p {{ color: var(--muted); margin-top: .25rem; }}
  .stats {{ display: flex; gap: 1rem; margin: 1.5rem 0; flex-wrap: wrap; }}
  .stat-card {{ background: var(--card); border: 1px solid var(--border); border-radius: .5rem;
    padding: .75rem 1.25rem; min-width: 100px; }}
  .stat-card .label {{ font-size: .75rem; text-transform: uppercase; color: var(--muted); }}
  .stat-card .value {{ font-size: 1.5rem; font-weight: 700; margin-top: .2rem; }}
  .log-entry {{ background: var(--card); border: 1px solid var(--border);
    border-radius: .5rem; padding: .75rem 1rem; margin-bottom: .5rem; }}
  .log-entry .meta {{ display: flex; gap: 1rem; align-items: center; margin-bottom: .3rem; }}
  .badge {{ font-size: .7rem; font-weight: 700; padding: .15rem .5rem; border-radius: 9999px;
    background: color-mix(in srgb, var(--level-color) 20%, transparent);
    color: var(--level-color); border: 1px solid var(--level-color); }}
  .ts {{ font-size: .75rem; color: var(--muted); font-family: monospace; }}
  .logger-name {{ font-size: .75rem; color: var(--muted); }}
  .message {{ font-size: .9rem; white-space: pre-wrap; word-break: break-word; }}
  .extra {{ font-size: .8rem; color: var(--muted); margin-top: .5rem; font-family: monospace;
    background: rgba(255,255,255,.03); padding: .4rem .6rem; border-radius: .3rem; }}
  input#search {{ width: 100%; padding: .6rem 1rem; background: var(--card); border: 1px solid var(--border);
    border-radius: .4rem; color: var(--text); font-size: .9rem; margin-bottom: 1rem; }}
  input#search:focus {{ outline: none; border-color: #3b82f6; }}
  .hidden {{ display: none; }}
  footer {{ margin-top: 2rem; text-align: center; font-size: .75rem; color: var(--muted); }}
</style>
</head>
<body>
<header>
  <h1>📋 FastLogger Report</h1>
  <p>Generated {generated_at} · {log_count} entries · Source: <code>{source}</code></p>
</header>
<div class="stats">
{stats_html}
</div>
<input id="search" type="text" placeholder="🔍 Search logs..." oninput="filterLogs(this.value)" />
<div id="log-container">
{entries_html}
</div>
<footer>Generated by <strong>python-fast-logger</strong></footer>
<script>
function filterLogs(q) {{
  q = q.toLowerCase();
  document.querySelectorAll('.log-entry').forEach(el => {{
    el.classList.toggle('hidden', q && !el.textContent.toLowerCase().includes(q));
  }});
}}
</script>
</body>
</html>
"""


def _load_records(filepath: str) -> list[dict[str, Any]]:
    records: list[dict[str, Any]] = []
    with open(filepath, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                records.append(json.loads(line))
            except json.JSONDecodeError:
                records.append({"level": "INFO", "message": line, "timestamp": ""})
    return records


def export_html(source_filepath: str, output_filepath: str) -> None:
    """Export a .fl session file to a self-contained, searchable HTML report."""
    records = _load_records(source_filepath)

    # Compute stats
    counts: dict[str, int] = {}
    for r in records:
        lvl = r.get("level", "INFO").upper()
        counts[lvl] = counts.get(lvl, 0) + 1

    stats_html_parts = []
    for lvl in ["DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"]:
        if counts.get(lvl, 0):
            color = _LEVEL_COLORS.get(lvl, "#64748b")
            stats_html_parts.append(
                f'  <div class="stat-card" style="--level-color:{color}">'
                f'<div class="label">{lvl}</div>'
                f'<div class="value" style="color:{color}">{counts[lvl]}</div>'
                f"</div>"
            )

    # Build entries
    entry_parts = []
    for r in records:
        lvl = r.get("level", "INFO").upper()
        color = _LEVEL_COLORS.get(lvl, "#64748b")
        ts = r.get("timestamp", "")
        msg = html_mod.escape(r.get("message", ""))
        name = html_mod.escape(r.get("logger", ""))
        extra = {
            k: v
            for k, v in r.items()
            if k not in ("level", "message", "timestamp", "logger", "exception")
        }
        extra_html = ""
        if extra:
            extra_json = html_mod.escape(json.dumps(extra, indent=2, default=str))
            extra_html = f'<div class="extra">{extra_json}</div>'
        exc_html = ""
        if r.get("exception"):
            exc_html = f'<div class="extra" style="color:#ef4444">{html_mod.escape(str(r["exception"]))}</div>'

        entry_parts.append(
            f'<div class="log-entry" style="border-left-color:{color}">'
            f'<div class="meta">'
            f'<span class="badge" style="--level-color:{color}">{lvl}</span>'
            f'<span class="ts">{ts}</span>'
            f'<span class="logger-name">{name}</span>'
            f"</div>"
            f'<div class="message">{msg}</div>'
            f"{extra_html}{exc_html}"
            f"</div>"
        )

    html_out = _HTML_TEMPLATE.format(
        title=html_mod.escape(os.path.basename(source_filepath)),
        generated_at=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        log_count=len(records),
        source=html_mod.escape(source_filepath),
        stats_html="\n".join(stats_html_parts),
        entries_html="\n".join(entry_parts),
    )

    with open(output_filepath, "w", encoding="utf-8") as f:
        f.write(html_out)


def export_markdown(source_filepath: str, output_filepath: str) -> None:
    """Export a .fl session file to a GitHub-Flavored Markdown log table."""
    records = _load_records(source_filepath)

    lines = [
        f"# FastLogger Report — `{os.path.basename(source_filepath)}`",
        f"",
        f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')} · {len(records)} entries",
        f"",
        f"| Timestamp | Level | Message |",
        f"|-----------|-------|---------|",
    ]

    for r in records:
        ts = r.get("timestamp", "")
        lvl = r.get("level", "INFO").upper()
        msg = r.get("message", "").replace("|", "\\|").replace("\n", " ")
        lines.append(f"| `{ts}` | **{lvl}** | {msg} |")

    with open(output_filepath, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
