"""
Built-in Log Viewer TUI for fast-logger.
Run with: python -m fast_logger.viewer <path_to_json_log>
"""

import sys
import json
from pathlib import Path
from typing import Any

try:
    from textual.app import App, ComposeResult  # type: ignore
    from textual.widgets import Header, Footer, DataTable  # type: ignore
    from textual.containers import Container  # type: ignore

    TEXTUAL_AVAILABLE = True
except ImportError:
    TEXTUAL_AVAILABLE = False

    class App:  # type: ignore[no-redef]
        pass

    ComposeResult = Any  # type: ignore


class LogViewer(App):
    """Textual TUI for viewing JSON structured logs generated by python-fast-logger."""

    TITLE = "Fast-Logger TUI"
    BINDINGS = [("q", "quit", "Quit"), ("r", "reload", "Reload File")]

    def __init__(self, log_path: str):
        super().__init__()
        self.log_path = Path(log_path)

    def compose(self) -> ComposeResult:
        yield Header()
        yield DataTable(id="logs_table")
        yield Footer()

    def on_mount(self) -> None:
        table = self.query_one(DataTable)
        table.cursor_type = "row"
        table.add_columns("Timestamp", "Level", "Module", "Message")
        self.load_logs()

    def load_logs(self) -> None:
        table = self.query_one(DataTable)
        table.clear()

        if not self.log_path.exists():
            table.add_row("", "ERROR", "", f"File not found: {self.log_path}")
            return

        with open(self.log_path, "r", encoding="utf-8") as f:
            for line in f:
                if not line.strip():
                    continue
                try:
                    data = json.loads(line)
                    ts = data.get("timestamp", "")
                    lvl = data.get("level", "")
                    mod = data.get("module", "")
                    msg = data.get("message", "")

                    # Truncate extremely long messages for the table
                    if len(msg) > 100:
                        msg = msg[:97] + "..."

                    table.add_row(ts, lvl, mod, msg)
                except Exception:
                    table.add_row("", "ERROR", "", "Failed to parse JSON log line.")

    def action_reload(self) -> None:
        """Action when user presses 'r'."""
        self.load_logs()


def main() -> None:
    if not TEXTUAL_AVAILABLE:
        print("Textual is required for the log viewer (pip install textual)")
        sys.exit(1)

    if len(sys.argv) < 2:
        print("Usage: python -m fast_logger.viewer <path_to_json_log>")
        sys.exit(1)

    app = LogViewer(sys.argv[1])
    app.run()


if __name__ == "__main__":
    main()
